# Generated by Terraform ("make cluster-up"). Do not edit: it is rewritten on every run.
[server]
${server.name} ansible_host=${server.public_ip} node_ip=${server.private_ip}

[agents]
%{ for agent in agents ~}
${agent.name} ansible_host=${agent.public_ip} node_ip=${agent.private_ip}
%{ endfor ~}

[k3s:children]
server
agents

[k3s:vars]
ansible_user=${user}
ansible_ssh_private_key_file=${key_file}
